//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.UserAccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class UserAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashPassword {
            get {
                return this.HashPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashPasswordField, value) != true)) {
                    this.HashPasswordField = value;
                    this.RaisePropertyChanged("HashPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccountService.IUserAccountSecureService")]
    public interface IUserAccountSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetAll", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetAllResponse")]
        ManagingSystem.UserAccountService.UserAccount[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetAll", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetById", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetByIdResponse")]
        ManagingSystem.UserAccountService.UserAccount GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetById", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetByEmployeeId", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetByEmployeeIdResponse")]
        ManagingSystem.UserAccountService.UserAccount GetByEmployeeId(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/GetByEmployeeId", ReplyAction="http://tempuri.org/IUserAccountSecureService/GetByEmployeeIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount> GetByEmployeeIdAsync(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/Create", ReplyAction="http://tempuri.org/IUserAccountSecureService/CreateResponse")]
        void Create(ManagingSystem.UserAccountService.UserAccount userAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/Create", ReplyAction="http://tempuri.org/IUserAccountSecureService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ManagingSystem.UserAccountService.UserAccount userAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/DeleteById", ReplyAction="http://tempuri.org/IUserAccountSecureService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/DeleteById", ReplyAction="http://tempuri.org/IUserAccountSecureService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/DeleteByEmployeeId", ReplyAction="http://tempuri.org/IUserAccountSecureService/DeleteByEmployeeIdResponse")]
        void DeleteByEmployeeId(int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccountSecureService/DeleteByEmployeeId", ReplyAction="http://tempuri.org/IUserAccountSecureService/DeleteByEmployeeIdResponse")]
        System.Threading.Tasks.Task DeleteByEmployeeIdAsync(int employeeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAccountSecureServiceChannel : ManagingSystem.UserAccountService.IUserAccountSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccountSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.UserAccountService.IUserAccountSecureService>, ManagingSystem.UserAccountService.IUserAccountSecureService {
        
        public UserAccountSecureServiceClient() {
        }
        
        public UserAccountSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccountSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccountSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.UserAccountService.UserAccount[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.UserAccountService.UserAccount GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public ManagingSystem.UserAccountService.UserAccount GetByEmployeeId(int employeeId) {
            return base.Channel.GetByEmployeeId(employeeId);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.UserAccountService.UserAccount> GetByEmployeeIdAsync(int employeeId) {
            return base.Channel.GetByEmployeeIdAsync(employeeId);
        }
        
        public void Create(ManagingSystem.UserAccountService.UserAccount userAccount) {
            base.Channel.Create(userAccount);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ManagingSystem.UserAccountService.UserAccount userAccount) {
            return base.Channel.CreateAsync(userAccount);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public void DeleteByEmployeeId(int employeeId) {
            base.Channel.DeleteByEmployeeId(employeeId);
        }
        
        public System.Threading.Tasks.Task DeleteByEmployeeIdAsync(int employeeId) {
            return base.Channel.DeleteByEmployeeIdAsync(employeeId);
        }
    }
}
