//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.BusStopOnLineService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusStopOnLine", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class BusStopOnLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusStopIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberStopOnLineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusStopId {
            get {
                return this.BusStopIdField;
            }
            set {
                if ((this.BusStopIdField.Equals(value) != true)) {
                    this.BusStopIdField = value;
                    this.RaisePropertyChanged("BusStopId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineId {
            get {
                return this.LineIdField;
            }
            set {
                if ((this.LineIdField.Equals(value) != true)) {
                    this.LineIdField = value;
                    this.RaisePropertyChanged("LineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberStopOnLine {
            get {
                return this.NumberStopOnLineField;
            }
            set {
                if ((this.NumberStopOnLineField.Equals(value) != true)) {
                    this.NumberStopOnLineField = value;
                    this.RaisePropertyChanged("NumberStopOnLine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopOnLineService.IBusStopOnLineSecureService")]
    public interface IBusStopOnLineSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/GetAllWithDeletedResponse")]
        ManagingSystem.BusStopOnLineService.BusStopOnLine[] GetAllWithDeleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/GetAllWithDeletedResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine[]> GetAllWithDeletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/Create", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/CreateResponse")]
        void Create(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/Create", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/Update", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/UpdateResponse")]
        void Update(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/Update", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/UndeleteByIdResponse")]
        void UndeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopOnLineSecureService/UndeleteByIdResponse")]
        System.Threading.Tasks.Task UndeleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopOnLineSecureServiceChannel : ManagingSystem.BusStopOnLineService.IBusStopOnLineSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopOnLineSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopOnLineService.IBusStopOnLineSecureService>, ManagingSystem.BusStopOnLineService.IBusStopOnLineSecureService {
        
        public BusStopOnLineSecureServiceClient() {
        }
        
        public BusStopOnLineSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopOnLineSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopOnLineSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopOnLineSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopOnLineService.BusStopOnLine[] GetAllWithDeleted() {
            return base.Channel.GetAllWithDeleted();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine[]> GetAllWithDeletedAsync() {
            return base.Channel.GetAllWithDeletedAsync();
        }
        
        public void Create(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine) {
            base.Channel.Create(busStopOnLine);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine) {
            return base.Channel.CreateAsync(busStopOnLine);
        }
        
        public void Update(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine) {
            base.Channel.Update(busStopOnLine);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopOnLineService.BusStopOnLine busStopOnLine) {
            return base.Channel.UpdateAsync(busStopOnLine);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public void UndeleteById(int id) {
            base.Channel.UndeleteById(id);
        }
        
        public System.Threading.Tasks.Task UndeleteByIdAsync(int id) {
            return base.Channel.UndeleteByIdAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopOnLineService.IBusStopOnLineService")]
    public interface IBusStopOnLineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineService/GetAll", ReplyAction="http://tempuri.org/IBusStopOnLineService/GetAllResponse")]
        ManagingSystem.BusStopOnLineService.BusStopOnLine[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineService/GetAll", ReplyAction="http://tempuri.org/IBusStopOnLineService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineService/GetById", ReplyAction="http://tempuri.org/IBusStopOnLineService/GetByIdResponse")]
        ManagingSystem.BusStopOnLineService.BusStopOnLine GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopOnLineService/GetById", ReplyAction="http://tempuri.org/IBusStopOnLineService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopOnLineServiceChannel : ManagingSystem.BusStopOnLineService.IBusStopOnLineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopOnLineServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopOnLineService.IBusStopOnLineService>, ManagingSystem.BusStopOnLineService.IBusStopOnLineService {
        
        public BusStopOnLineServiceClient() {
        }
        
        public BusStopOnLineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopOnLineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopOnLineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopOnLineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopOnLineService.BusStopOnLine[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.BusStopOnLineService.BusStopOnLine GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopOnLineService.BusStopOnLine> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
