//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.BusStopTypeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusStop", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class BusStop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusStopTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusStopTypeId {
            get {
                return this.BusStopTypeIdField;
            }
            set {
                if ((this.BusStopTypeIdField.Equals(value) != true)) {
                    this.BusStopTypeIdField = value;
                    this.RaisePropertyChanged("BusStopTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopTypeService.IBusStopSecureService")]
    public interface IBusStopSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopSecureService/GetAllWithDeletedResponse")]
        ManagingSystem.BusStopTypeService.BusStop[] GetAllWithDeleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopSecureService/GetAllWithDeletedResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop[]> GetAllWithDeletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/Create", ReplyAction="http://tempuri.org/IBusStopSecureService/CreateResponse")]
        void Create(ManagingSystem.BusStopTypeService.BusStop busStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/Create", ReplyAction="http://tempuri.org/IBusStopSecureService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopTypeService.BusStop busStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/Update", ReplyAction="http://tempuri.org/IBusStopSecureService/UpdateResponse")]
        void Update(ManagingSystem.BusStopTypeService.BusStop busStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/Update", ReplyAction="http://tempuri.org/IBusStopSecureService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopTypeService.BusStop busStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopSecureService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopSecureService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopSecureService/UndeleteByIdResponse")]
        void UndeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopSecureService/UndeleteByIdResponse")]
        System.Threading.Tasks.Task UndeleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopSecureServiceChannel : ManagingSystem.BusStopTypeService.IBusStopSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopTypeService.IBusStopSecureService>, ManagingSystem.BusStopTypeService.IBusStopSecureService {
        
        public BusStopSecureServiceClient() {
        }
        
        public BusStopSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopTypeService.BusStop[] GetAllWithDeleted() {
            return base.Channel.GetAllWithDeleted();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop[]> GetAllWithDeletedAsync() {
            return base.Channel.GetAllWithDeletedAsync();
        }
        
        public void Create(ManagingSystem.BusStopTypeService.BusStop busStop) {
            base.Channel.Create(busStop);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopTypeService.BusStop busStop) {
            return base.Channel.CreateAsync(busStop);
        }
        
        public void Update(ManagingSystem.BusStopTypeService.BusStop busStop) {
            base.Channel.Update(busStop);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopTypeService.BusStop busStop) {
            return base.Channel.UpdateAsync(busStop);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public void UndeleteById(int id) {
            base.Channel.UndeleteById(id);
        }
        
        public System.Threading.Tasks.Task UndeleteByIdAsync(int id) {
            return base.Channel.UndeleteByIdAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopTypeService.IBusStopService")]
    public interface IBusStopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopService/GetAll", ReplyAction="http://tempuri.org/IBusStopService/GetAllResponse")]
        ManagingSystem.BusStopTypeService.BusStop[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopService/GetAll", ReplyAction="http://tempuri.org/IBusStopService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopService/GetById", ReplyAction="http://tempuri.org/IBusStopService/GetByIdResponse")]
        ManagingSystem.BusStopTypeService.BusStop GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopService/GetById", ReplyAction="http://tempuri.org/IBusStopService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopServiceChannel : ManagingSystem.BusStopTypeService.IBusStopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopTypeService.IBusStopService>, ManagingSystem.BusStopTypeService.IBusStopService {
        
        public BusStopServiceClient() {
        }
        
        public BusStopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopTypeService.BusStop[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.BusStopTypeService.BusStop GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStop> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
