//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.BusStopTypeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusStopType", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class BusStopType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopTypeService.IBusStopTypeSecureService")]
    public interface IBusStopTypeSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/GetAllWithDeletedResponse")]
        ManagingSystem.BusStopTypeService.BusStopType[] GetAllWithDeleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/GetAllWithDeletedResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType[]> GetAllWithDeletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/Create", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/CreateResponse")]
        void Create(ManagingSystem.BusStopTypeService.BusStopType busStopType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/Create", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopTypeService.BusStopType busStopType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/Update", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/UpdateResponse")]
        void Update(ManagingSystem.BusStopTypeService.BusStopType busStopType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/Update", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopTypeService.BusStopType busStopType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/DeleteById", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/UndeleteByIdResponse")]
        void UndeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeSecureService/UndeleteById", ReplyAction="http://tempuri.org/IBusStopTypeSecureService/UndeleteByIdResponse")]
        System.Threading.Tasks.Task UndeleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopTypeSecureServiceChannel : ManagingSystem.BusStopTypeService.IBusStopTypeSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopTypeSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopTypeService.IBusStopTypeSecureService>, ManagingSystem.BusStopTypeService.IBusStopTypeSecureService {
        
        public BusStopTypeSecureServiceClient() {
        }
        
        public BusStopTypeSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopTypeSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopTypeSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopTypeSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopTypeService.BusStopType[] GetAllWithDeleted() {
            return base.Channel.GetAllWithDeleted();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType[]> GetAllWithDeletedAsync() {
            return base.Channel.GetAllWithDeletedAsync();
        }
        
        public void Create(ManagingSystem.BusStopTypeService.BusStopType busStopType) {
            base.Channel.Create(busStopType);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ManagingSystem.BusStopTypeService.BusStopType busStopType) {
            return base.Channel.CreateAsync(busStopType);
        }
        
        public void Update(ManagingSystem.BusStopTypeService.BusStopType busStopType) {
            base.Channel.Update(busStopType);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ManagingSystem.BusStopTypeService.BusStopType busStopType) {
            return base.Channel.UpdateAsync(busStopType);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public void UndeleteById(int id) {
            base.Channel.UndeleteById(id);
        }
        
        public System.Threading.Tasks.Task UndeleteByIdAsync(int id) {
            return base.Channel.UndeleteByIdAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusStopTypeService.IBusStopTypeService")]
    public interface IBusStopTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeService/GetAll", ReplyAction="http://tempuri.org/IBusStopTypeService/GetAllResponse")]
        ManagingSystem.BusStopTypeService.BusStopType[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeService/GetAll", ReplyAction="http://tempuri.org/IBusStopTypeService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeService/GetById", ReplyAction="http://tempuri.org/IBusStopTypeService/GetByIdResponse")]
        ManagingSystem.BusStopTypeService.BusStopType GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusStopTypeService/GetById", ReplyAction="http://tempuri.org/IBusStopTypeService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusStopTypeServiceChannel : ManagingSystem.BusStopTypeService.IBusStopTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusStopTypeServiceClient : System.ServiceModel.ClientBase<ManagingSystem.BusStopTypeService.IBusStopTypeService>, ManagingSystem.BusStopTypeService.IBusStopTypeService {
        
        public BusStopTypeServiceClient() {
        }
        
        public BusStopTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusStopTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusStopTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.BusStopTypeService.BusStopType[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.BusStopTypeService.BusStopType GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.BusStopTypeService.BusStopType> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
