//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.LineService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Line", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LineService.ILineSecureService")]
    public interface ILineSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/ILineSecureService/GetAllWithDeletedResponse")]
        ManagingSystem.LineService.Line[] GetAllWithDeleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/GetAllWithDeleted", ReplyAction="http://tempuri.org/ILineSecureService/GetAllWithDeletedResponse")]
        System.Threading.Tasks.Task<ManagingSystem.LineService.Line[]> GetAllWithDeletedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/Create", ReplyAction="http://tempuri.org/ILineSecureService/CreateResponse")]
        void Create(ManagingSystem.LineService.Line line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/Create", ReplyAction="http://tempuri.org/ILineSecureService/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ManagingSystem.LineService.Line line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/Update", ReplyAction="http://tempuri.org/ILineSecureService/UpdateResponse")]
        void Update(ManagingSystem.LineService.Line line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/Update", ReplyAction="http://tempuri.org/ILineSecureService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ManagingSystem.LineService.Line line);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/DeleteById", ReplyAction="http://tempuri.org/ILineSecureService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/DeleteById", ReplyAction="http://tempuri.org/ILineSecureService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/UndeleteById", ReplyAction="http://tempuri.org/ILineSecureService/UndeleteByIdResponse")]
        void UndeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineSecureService/UndeleteById", ReplyAction="http://tempuri.org/ILineSecureService/UndeleteByIdResponse")]
        System.Threading.Tasks.Task UndeleteByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILineSecureServiceChannel : ManagingSystem.LineService.ILineSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LineSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.LineService.ILineSecureService>, ManagingSystem.LineService.ILineSecureService {
        
        public LineSecureServiceClient() {
        }
        
        public LineSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LineSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.LineService.Line[] GetAllWithDeleted() {
            return base.Channel.GetAllWithDeleted();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.LineService.Line[]> GetAllWithDeletedAsync() {
            return base.Channel.GetAllWithDeletedAsync();
        }
        
        public void Create(ManagingSystem.LineService.Line line) {
            base.Channel.Create(line);
        }
        
        public System.Threading.Tasks.Task CreateAsync(ManagingSystem.LineService.Line line) {
            return base.Channel.CreateAsync(line);
        }
        
        public void Update(ManagingSystem.LineService.Line line) {
            base.Channel.Update(line);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ManagingSystem.LineService.Line line) {
            return base.Channel.UpdateAsync(line);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public void UndeleteById(int id) {
            base.Channel.UndeleteById(id);
        }
        
        public System.Threading.Tasks.Task UndeleteByIdAsync(int id) {
            return base.Channel.UndeleteByIdAsync(id);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LineService.ILineService")]
    public interface ILineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineService/GetAll", ReplyAction="http://tempuri.org/ILineService/GetAllResponse")]
        ManagingSystem.LineService.Line[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineService/GetAll", ReplyAction="http://tempuri.org/ILineService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.LineService.Line[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineService/GetById", ReplyAction="http://tempuri.org/ILineService/GetByIdResponse")]
        ManagingSystem.LineService.Line GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILineService/GetById", ReplyAction="http://tempuri.org/ILineService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.LineService.Line> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILineServiceChannel : ManagingSystem.LineService.ILineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LineServiceClient : System.ServiceModel.ClientBase<ManagingSystem.LineService.ILineService>, ManagingSystem.LineService.ILineService {
        
        public LineServiceClient() {
        }
        
        public LineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.LineService.Line[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.LineService.Line[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.LineService.Line GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.LineService.Line> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
    }
}
