//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagingSystem.PurchaseTicketSecureService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseTicket", Namespace="Wpk.Entities")]
    [System.SerializableAttribute()]
    public partial class PurchaseTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfPurchaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiscountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentIdentificationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameTicketOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameTicketOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfPurchase {
            get {
                return this.DateOfPurchaseField;
            }
            set {
                if ((this.DateOfPurchaseField.Equals(value) != true)) {
                    this.DateOfPurchaseField = value;
                    this.RaisePropertyChanged("DateOfPurchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiscountId {
            get {
                return this.DiscountIdField;
            }
            set {
                if ((this.DiscountIdField.Equals(value) != true)) {
                    this.DiscountIdField = value;
                    this.RaisePropertyChanged("DiscountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentIdentificationNumber {
            get {
                return this.DocumentIdentificationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentIdentificationNumberField, value) != true)) {
                    this.DocumentIdentificationNumberField = value;
                    this.RaisePropertyChanged("DocumentIdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameTicketOwner {
            get {
                return this.FirstNameTicketOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameTicketOwnerField, value) != true)) {
                    this.FirstNameTicketOwnerField = value;
                    this.RaisePropertyChanged("FirstNameTicketOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameTicketOwner {
            get {
                return this.LastNameTicketOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameTicketOwnerField, value) != true)) {
                    this.LastNameTicketOwnerField = value;
                    this.RaisePropertyChanged("LastNameTicketOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((this.TicketIdField.Equals(value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchaseTicketSecureService.IPurchaseTicketSecureService")]
    public interface IPurchaseTicketSecureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetAll", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetAllResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetAll", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetAllResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetToDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetToDateResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetToDate(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetToDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetToDateResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetToDateAsync(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetAfterDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetAfterDateResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetAfterDate(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetAfterDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetAfterDateResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetAfterDateAsync(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByFirstName", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByFirstNameResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByFirstName(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByFirstName", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByFirstNameResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByFirstNameAsync(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByLastName", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByLastNameResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByLastName(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByLastName", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByLastNameResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByLastNameAsync(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetFromDevice", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetFromDeviceResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetFromDevice(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetFromDevice", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetFromDeviceResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetFromDeviceAsync(string deviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetById", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByIdResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetById", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByCustomerId", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByCustomerIdResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByCustomerId(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetByCustomerId", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetByCustomerIdResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByCustomerIdAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetFromDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetFromDateResponse")]
        ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetFromDate(System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseTicketSecureService/GetFromDate", ReplyAction="http://tempuri.org/IPurchaseTicketSecureService/GetFromDateResponse")]
        System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetFromDateAsync(System.DateTime dateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseTicketSecureServiceChannel : ManagingSystem.PurchaseTicketSecureService.IPurchaseTicketSecureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseTicketSecureServiceClient : System.ServiceModel.ClientBase<ManagingSystem.PurchaseTicketSecureService.IPurchaseTicketSecureService>, ManagingSystem.PurchaseTicketSecureService.IPurchaseTicketSecureService {
        
        public PurchaseTicketSecureServiceClient() {
        }
        
        public PurchaseTicketSecureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseTicketSecureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseTicketSecureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseTicketSecureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetToDate(System.DateTime dateTime) {
            return base.Channel.GetToDate(dateTime);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetToDateAsync(System.DateTime dateTime) {
            return base.Channel.GetToDateAsync(dateTime);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetAfterDate(System.DateTime dateTime) {
            return base.Channel.GetAfterDate(dateTime);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetAfterDateAsync(System.DateTime dateTime) {
            return base.Channel.GetAfterDateAsync(dateTime);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByFirstName(string firstName) {
            return base.Channel.GetByFirstName(firstName);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByFirstNameAsync(string firstName) {
            return base.Channel.GetByFirstNameAsync(firstName);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByLastName(string lastName) {
            return base.Channel.GetByLastName(lastName);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByLastNameAsync(string lastName) {
            return base.Channel.GetByLastNameAsync(lastName);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetFromDevice(string deviceId) {
            return base.Channel.GetFromDevice(deviceId);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetFromDeviceAsync(string deviceId) {
            return base.Channel.GetFromDeviceAsync(deviceId);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetByCustomerId(int customerId) {
            return base.Channel.GetByCustomerId(customerId);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetByCustomerIdAsync(int customerId) {
            return base.Channel.GetByCustomerIdAsync(customerId);
        }
        
        public ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[] GetFromDate(System.DateTime dateTime) {
            return base.Channel.GetFromDate(dateTime);
        }
        
        public System.Threading.Tasks.Task<ManagingSystem.PurchaseTicketSecureService.PurchaseTicket[]> GetFromDateAsync(System.DateTime dateTime) {
            return base.Channel.GetFromDateAsync(dateTime);
        }
    }
}
